language: php
php:
  - '7.0'
  - '7.1'
before_install:
 - git clone git@github.com:phpredis/phpredis.git redis
 - cd redis
 - phpize
 - ./configure [--enable-redis-igbinary]
 - make && make install
script: phpunit --configuration phpunit.xml tests/