language: php
php:
  - '7.0'
  - '7.1'
before_install:
 - git clone https://github.com/phpredis/phpredis.git
 - cd phpredis
 - phpize
 - ./configure
 - make && make install
 - cd ..
script: phpunit --configuration phpunit.xml tests/